### ISSUE TITLE
`flushQueue` bombing out in integration tests

### ISSUE THREAD

**Issue by patrickberkeley** [pzuraq/liquid-tether#24] opened 2015-11-06 17:14 UTC
For integration tests I'm getting an error on https://github.com/pzuraq/liquid-tether/blob/420b2f35c9fadfb8653f7b2e3f3c50932df42cec/addon/services/liquid-target.js#L49.

The error is `Uncaught TypeError: Cannot read property 'items' of undefined`:

![](https://s3.amazonaws.com/screen-caps/sKiYZ.png)

I logged it out and somehow [`removeItem()`](https://github.com/pzuraq/liquid-tether/blob/420b2f35c9fadfb8653f7b2e3f3c50932df42cec/addon/services/liquid-target.js#L30-L35) is able to push an object onto the queue that has an `undefined` target.

**Comment by jordpo** [comment] 2015-11-06 17:15
:+1: this

**Comment by pzuraq** [comment] 2015-11-10 21:52
Interesting, @patrickberkeley what version of Ember are you using?

**Comment by patrickberkeley** [comment] 2015-11-10 22:07
We're on 2.0.2

**Comment by pzuraq** [comment] 2015-11-10 22:15
Cool, will take a look. My gut feeling is that something is getting scheduled on the runloop and running after the container/service has been destroyed, have run into similar problems on integration tests before.

**Comment by patrickberkeley** [comment] 2015-11-10 22:28
Okay, interesting. Your scenario seems plausible from what I was seeing
while debugging.

**Comment by pzuraq** [comment] 2015-11-19 21:03
@patrickberkeley @jordpo I'm having trouble reproducing this bug, can you post an example test that causes the bug?

**Comment by pzuraq** [comment] 2015-12-15 19:54
@patrickberkeley @jordpo Any word on this? I consider Ember 2.0 compatibility a high priority and this issue has been outstanding for a while, but I have not been able to reproduce.

**Comment by pzuraq** [comment] 2016-01-04 19:32
Closing this issue as I cannot reproduce locally. Feel free to reopen if it is still occurring for you, definitely a priority.

**Closed by pzuraq** 2016-01-04 19:32 UTC
