### ISSUE TITLE
component's size in modal on didInsertElement

### ISSUE THREAD

**Issue by BenjaminHorn** [pzuraq/liquid-tether#39] opened 2016-01-30 19:35 UTC
I try to measure the width of a table on didInsertElement. Unfortunately it gives back a negative number. I guess the table is outside the window, and is not rendered properly at the moment when I try to get its width.

```javascript
   didInsertElement: function(){
    console.log('table');
    this.$('table').colResizable();
    var widths = this.get('widths');
    if (widths) {
      this.setWidths(widths);
    }

  },
  setWidths: function(widths) {
    var width = 0, columns = 0, widths = widths.split(',');
    this.$('table tr th').each(function(i, v){
      columns++;
      width += $(v).width();
      console.log($(v));
    });
    // desperate attempt to fix it
    if (width === 0) {
      width = this.$('table').outerWidth();
    }
    console.log(width);
    this.$('table tr th').each(function(i, v){
      var w = (widths[i] * width) / 100;
      $(v).width(w);

    });    
  },
  didRender: function(){
    console.log('didRender');
    this.$('table').colResizable({disable: true});
    this.$('table').colResizable();
  },
```

If I call setWidths from didRender, then it works fine, I just have to make my table component rerender after it has already appear in full size in the model. Just for test I do it by mouseclick, but I should find a way to do it automatically
- when the animation is ended, and I have the final size of the table
- only once, at the begging of the component's lifecycle

**Comment by pzuraq** [comment] 2016-01-30 20:50
So the way `liquid-fire` works, it actually inserts the element and then animates it, which oftentimes screws up this type of logic. I actually had to integrate pretty deeply with `liquid-versions` to overcome this problem with animating the targets, there is some self-cleaning logic that has to be applied and it has to be done after animations are complete.

The hooks are in there right now, the question is where should we put them. Right now, when animation starts we do `target.set('isAnimating', true)` for the target that is currently animating. When animations are complete, we call `liquidTargetService.didAnimate()` which then flushes the animation queue and cleans up any empty targets.

Fundamentally the problem is that the `liquid-tether` and your component do not have any knowledge about when the animation finishes. We could a hook directly in `liquidTargetService.didAnimate()`, but that only gets us to the `liquid-tether`. So how do we pass that event to your component..

I'll have to think on this. Definitely think it would be very useful, we should look into if anyone has encountered a similar problem with `liquid-fire` itself.

**Comment by BenjaminHorn** [comment] 2016-01-30 22:30
I think it worth to mention, that this strategy works on routes with liquid-fire outlets. Only modal routes mess things up.

**Comment by pzuraq** [comment] 2016-02-01 19:55
Definitely worth mentioning. That may have to do with the fact that liquid-fire outlets usually have pretty standard rendering rules, just using position relative/absolute to move things around, whereas liquid-tether has to do a fair amount of styling to position things.

Does it work when you use `liquid-wormhole`? I'd be really interested to see if this is a problem caused by `Tether.js`.

**Comment by BenjaminHorn** [comment] 2016-02-02 00:43
> Does it work when you use liquid-wormhole?

What do you mean by this? 

Here is a screenshot of the structure of the page, if it helps.
![image](https://cloud.githubusercontent.com/assets/5570232/12736176/4c26c0e6-c94e-11e5-8624-7b0800fc3ffb.png)

If it needed, I can make a minimalistic repository to demonstrate the problem.

**Comment by pzuraq** [comment] 2016-02-02 20:35
A minimalistic example repo would be great if you have the time, but I'm pretty sure that won't be necessary. I'm thinking that the issue is caused by the styles that either liquid-tether or Tether.js applies to the container elements to position them on the page.

Can you try replacing your `{{#liquid-tether}}` with a `{{#liquid-wormhole}}`? It's the exact same component, but it doesn't use Tether.js so we can isolate the problem a little bit more.

**Comment by BenjaminHorn** [comment] 2016-02-02 21:19
I replaced the model component to `{{#liquid-wormhole}}` but it gives the exact same value (-64) for `width`

**Comment by pzuraq** [comment] 2016-02-02 22:09
Ok, then the problem is definitely being caused by `liquid-tether`s CSS. I'll look into it asap and see if I can come up with a solution. Ideally you won't have to do anything and `didInsertElement` will work as expected.

**Comment by BenjaminHorn** [comment] 2016-02-02 22:26
@pzuraq great, thank you!

**Comment by BenjaminHorn** [comment] 2016-02-19 12:31
@pzuraq any news on this?

**Comment by pzuraq** [comment] 2016-02-19 18:16
Been super busy the past couple weeks, have a new project that I've been working on. I'll have some time this weekend and am planning to take a look and get to the bottom of this then.

Will keep you posted, sorry about the delay!

**Comment by BenjaminHorn** [comment] 2016-02-19 19:02
@pzuraq  no problem, and thank you very much!

**Comment by pzuraq** [comment] 2016-02-21 19:13
@BenjaminHorn So I've been trying to reproduce this issue and I think the reason why it's happening is when the element is first inserted into the DOM, it is hidden with `display: none;`. The element is then moved to the top level, so Tether.js can position it and liquid-tether can animate it. 

Unfortunately I don't really see a direct way around this. Ideally you would not set the width the container programmatically and instead let it be determined by the parent element, but that may not work with the jQuery plugin that you are using.

**Comment by pzuraq** [comment] 2016-03-12 02:13
@BenjaminHorn Closing this issue for now. Let me know if you figure out a way around the problem, I don't believe this is in the scope of `liquid-tether` unfortunately.

**Closed by pzuraq** 2016-03-12 02:13 UTC
